/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IQuizzdleReferal__factory } from "./IQuizzdleReferal__factory";
export { Quizzdle__factory } from "./Quizzdle__factory";
