/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IQuizzdleReferal,
  IQuizzdleReferalInterface,
} from "../../Quizzdle.sol/IQuizzdleReferal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "referredBy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IQuizzdleReferal__factory {
  static readonly abi = _abi;
  static createInterface(): IQuizzdleReferalInterface {
    return new Interface(_abi) as IQuizzdleReferalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IQuizzdleReferal {
    return new Contract(address, _abi, runner) as unknown as IQuizzdleReferal;
  }
}
