/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as quizzdleSol from "./Quizzdle.sol";
export { GmQuizzdle__factory } from "./GmQuizzdle__factory";
export { QuizzdleReferal__factory } from "./QuizzdleReferal__factory";
