/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Quizzdle {
  export type SaltedGuessStruct = {
    saltedGuessHash: BytesLike;
    timestamp: BigNumberish;
    isCorrect: boolean;
  };

  export type SaltedGuessStructOutput = [
    saltedGuessHash: string,
    timestamp: bigint,
    isCorrect: boolean
  ] & { saltedGuessHash: string; timestamp: bigint; isCorrect: boolean };
}

export interface QuizzdleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addBonusForTomorrow"
      | "addCollection"
      | "addDailyBonus"
      | "claimAllWinnerRewards"
      | "claimReferralRewards"
      | "claimWinnerRewards"
      | "claimedDays"
      | "collectionExists"
      | "dailyBonus"
      | "dailyRevenue"
      | "dayFinalized"
      | "emergencyWithdraw"
      | "feePerGuess"
      | "flagReason"
      | "flagWallet"
      | "flaggedWallets"
      | "getAttemptsToday"
      | "getCommitment"
      | "getCurrentDay"
      | "getDayPool"
      | "getPendingWinnerRewards"
      | "getPlayerDailyGuesses"
      | "getTomorrowPool"
      | "getTotalPendingRewards"
      | "getTotalReserved"
      | "getUserSession"
      | "globalTotalPaid"
      | "globalTotalWins"
      | "hasWonToday"
      | "isWalletFlagged"
      | "owner"
      | "playerDailyGuesses"
      | "playerTotalWinsPerDay"
      | "referralContract"
      | "referralRewards"
      | "removeCollection"
      | "resetDayStats"
      | "resetRewardCounters"
      | "rewardPerWinPerDay"
      | "server"
      | "setFee"
      | "setReferralContract"
      | "setServer"
      | "submitSaltedGuess"
      | "totalFlaggedWallets"
      | "totalPaid"
      | "totalReferralEarned"
      | "totalReferralRewards"
      | "totalReferralsClaimed"
      | "totalWinnerRewardsClaimed"
      | "totalWinnerRewardsDistributed"
      | "totalWins"
      | "totalWinsPerDay"
      | "unflagWallet"
      | "userSessions"
      | "winsPerCollection"
      | "winsPerDayPerCollection"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommitmentSet"
      | "DailyBonusAdded"
      | "SaltedGuessMade"
      | "WalletFlagged"
      | "WalletUnflagged"
      | "WinRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addBonusForTomorrow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCollection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addDailyBonus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAllWinnerRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReferralRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnerRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedDays",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyBonus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dayFinalized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feePerGuess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flagReason",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flagWallet",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "flaggedWallets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttemptsToday",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDayPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingWinnerRewards",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerDailyGuesses",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTomorrowPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPendingRewards",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalReserved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSession",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "globalTotalPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalTotalWins",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasWonToday",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isWalletFlagged",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerDailyGuesses",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerTotalWinsPerDay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "referralContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCollection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetDayStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetRewardCounters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPerWinPerDay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "server", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferralContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setServer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSaltedGuess",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFlaggedWallets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPaid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReferralEarned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReferralRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReferralsClaimed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWinnerRewardsClaimed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWinnerRewardsDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWinsPerDay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unflagWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userSessions",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winsPerCollection",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winsPerDayPerCollection",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addBonusForTomorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDailyBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAllWinnerRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReferralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnerRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectionExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dailyBonus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dailyRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dayFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feePerGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flagReason", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flagWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "flaggedWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttemptsToday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDayPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingWinnerRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerDailyGuesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTomorrowPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalReserved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalTotalPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalTotalWins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasWonToday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWalletFlagged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerDailyGuesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerTotalWinsPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetDayStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetRewardCounters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPerWinPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "server", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReferralContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setServer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitSaltedGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFlaggedWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalPaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalReferralEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReferralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReferralsClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWinnerRewardsClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWinnerRewardsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalWins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalWinsPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unflagWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winsPerCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winsPerDayPerCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CommitmentSetEvent {
  export type InputTuple = [
    player: AddressLike,
    collectionId: BigNumberish,
    day: BigNumberish,
    commitment: BytesLike
  ];
  export type OutputTuple = [
    player: string,
    collectionId: bigint,
    day: bigint,
    commitment: string
  ];
  export interface OutputObject {
    player: string;
    collectionId: bigint;
    day: bigint;
    commitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyBonusAddedEvent {
  export type InputTuple = [
    day: BigNumberish,
    amount: BigNumberish,
    addedBy: AddressLike
  ];
  export type OutputTuple = [day: bigint, amount: bigint, addedBy: string];
  export interface OutputObject {
    day: bigint;
    amount: bigint;
    addedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaltedGuessMadeEvent {
  export type InputTuple = [
    player: AddressLike,
    collectionId: BigNumberish,
    saltedHash: BytesLike,
    isCorrect: boolean,
    attempts: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    collectionId: bigint,
    saltedHash: string,
    isCorrect: boolean,
    attempts: bigint
  ];
  export interface OutputObject {
    player: string;
    collectionId: bigint;
    saltedHash: string;
    isCorrect: boolean;
    attempts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletFlaggedEvent {
  export type InputTuple = [wallet: AddressLike, reason: string];
  export type OutputTuple = [wallet: string, reason: string];
  export interface OutputObject {
    wallet: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletUnflaggedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinRecordedEvent {
  export type InputTuple = [
    player: AddressLike,
    collectionId: BigNumberish,
    day: BigNumberish
  ];
  export type OutputTuple = [player: string, collectionId: bigint, day: bigint];
  export interface OutputObject {
    player: string;
    collectionId: bigint;
    day: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Quizzdle extends BaseContract {
  connect(runner?: ContractRunner | null): Quizzdle;
  waitForDeployment(): Promise<this>;

  interface: QuizzdleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addBonusForTomorrow: TypedContractMethod<[], [void], "payable">;

  addCollection: TypedContractMethod<
    [_collectionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addDailyBonus: TypedContractMethod<[_day: BigNumberish], [void], "payable">;

  claimAllWinnerRewards: TypedContractMethod<
    [_maxDaysToCheck: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimReferralRewards: TypedContractMethod<[], [void], "nonpayable">;

  claimWinnerRewards: TypedContractMethod<
    [_day: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimedDays: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  collectionExists: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  dailyBonus: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dailyRevenue: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dayFinalized: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  emergencyWithdraw: TypedContractMethod<
    [_to: AddressLike],
    [void],
    "nonpayable"
  >;

  feePerGuess: TypedContractMethod<[], [bigint], "view">;

  flagReason: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  flagWallet: TypedContractMethod<
    [_wallet: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  flaggedWallets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getAttemptsToday: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [bigint],
    "view"
  >;

  getCommitment: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [string],
    "view"
  >;

  getCurrentDay: TypedContractMethod<[], [bigint], "view">;

  getDayPool: TypedContractMethod<
    [_day: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        totalPool: bigint;
        winnersPool: bigint;
        isFinalized: boolean;
        totalWins: bigint;
      }
    ],
    "view"
  >;

  getPendingWinnerRewards: TypedContractMethod<
    [_player: AddressLike, _day: BigNumberish],
    [bigint],
    "view"
  >;

  getPlayerDailyGuesses: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish, _day: BigNumberish],
    [Quizzdle.SaltedGuessStructOutput[]],
    "view"
  >;

  getTomorrowPool: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalPool: bigint;
        winnersPool: bigint;
        day: bigint;
      }
    ],
    "view"
  >;

  getTotalPendingRewards: TypedContractMethod<
    [_player: AddressLike, _maxDaysToCheck: BigNumberish],
    [[bigint, bigint] & { totalPending: bigint; unclaimedDaysCount: bigint }],
    "view"
  >;

  getTotalReserved: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalReserved: bigint;
        reservedForReferrals: bigint;
        reservedForWinners: bigint;
        reservedForUnfinalized: bigint;
      }
    ],
    "view"
  >;

  getUserSession: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish, _day: BigNumberish],
    [
      [string, boolean, bigint] & {
        commitment: string;
        hasWonToday: boolean;
        attemptsToday: bigint;
      }
    ],
    "view"
  >;

  globalTotalPaid: TypedContractMethod<[], [bigint], "view">;

  globalTotalWins: TypedContractMethod<[], [bigint], "view">;

  hasWonToday: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [boolean],
    "view"
  >;

  isWalletFlagged: TypedContractMethod<
    [_wallet: AddressLike],
    [[boolean, string] & { flagged: boolean; reason: string }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  playerDailyGuesses: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish
    ],
    [
      [string, bigint, boolean] & {
        saltedGuessHash: string;
        timestamp: bigint;
        isCorrect: boolean;
      }
    ],
    "view"
  >;

  playerTotalWinsPerDay: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  referralContract: TypedContractMethod<[], [string], "view">;

  referralRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  removeCollection: TypedContractMethod<
    [_collectionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resetDayStats: TypedContractMethod<
    [_day: BigNumberish],
    [void],
    "nonpayable"
  >;

  resetRewardCounters: TypedContractMethod<[], [void], "nonpayable">;

  rewardPerWinPerDay: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  server: TypedContractMethod<[], [string], "view">;

  setFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  setReferralContract: TypedContractMethod<
    [_contract: AddressLike],
    [void],
    "nonpayable"
  >;

  setServer: TypedContractMethod<[_server: AddressLike], [void], "nonpayable">;

  submitSaltedGuess: TypedContractMethod<
    [
      _collectionId: BigNumberish,
      _saltedGuess: BytesLike,
      _commitment: BytesLike,
      _serverSignature: BytesLike,
      _shouldFlag: boolean
    ],
    [[boolean, bigint] & { isCorrect: boolean; attempts: bigint }],
    "payable"
  >;

  totalFlaggedWallets: TypedContractMethod<[], [bigint], "view">;

  totalPaid: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalReferralEarned: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  totalReferralRewards: TypedContractMethod<[], [bigint], "view">;

  totalReferralsClaimed: TypedContractMethod<[], [bigint], "view">;

  totalWinnerRewardsClaimed: TypedContractMethod<[], [bigint], "view">;

  totalWinnerRewardsDistributed: TypedContractMethod<[], [bigint], "view">;

  totalWins: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalWinsPerDay: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  unflagWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  userSessions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[string, boolean] & { commitment: string; hasWonToday: boolean }],
    "view"
  >;

  winsPerCollection: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  winsPerDayPerCollection: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdraw: TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addBonusForTomorrow"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "addCollection"
  ): TypedContractMethod<[_collectionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addDailyBonus"
  ): TypedContractMethod<[_day: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "claimAllWinnerRewards"
  ): TypedContractMethod<[_maxDaysToCheck: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReferralRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnerRewards"
  ): TypedContractMethod<[_day: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedDays"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectionExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "dailyBonus"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyRevenue"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dayFinalized"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feePerGuess"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "flagReason"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "flagWallet"
  ): TypedContractMethod<
    [_wallet: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flaggedWallets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAttemptsToday"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCommitment"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDayPool"
  ): TypedContractMethod<
    [_day: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        totalPool: bigint;
        winnersPool: bigint;
        isFinalized: boolean;
        totalWins: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingWinnerRewards"
  ): TypedContractMethod<
    [_player: AddressLike, _day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerDailyGuesses"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish, _day: BigNumberish],
    [Quizzdle.SaltedGuessStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTomorrowPool"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalPool: bigint;
        winnersPool: bigint;
        day: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPendingRewards"
  ): TypedContractMethod<
    [_player: AddressLike, _maxDaysToCheck: BigNumberish],
    [[bigint, bigint] & { totalPending: bigint; unclaimedDaysCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalReserved"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalReserved: bigint;
        reservedForReferrals: bigint;
        reservedForWinners: bigint;
        reservedForUnfinalized: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSession"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish, _day: BigNumberish],
    [
      [string, boolean, bigint] & {
        commitment: string;
        hasWonToday: boolean;
        attemptsToday: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalTotalPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalTotalWins"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasWonToday"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isWalletFlagged"
  ): TypedContractMethod<
    [_wallet: AddressLike],
    [[boolean, string] & { flagged: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playerDailyGuesses"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish
    ],
    [
      [string, bigint, boolean] & {
        saltedGuessHash: string;
        timestamp: bigint;
        isCorrect: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerTotalWinsPerDay"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "referralContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referralRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeCollection"
  ): TypedContractMethod<[_collectionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetDayStats"
  ): TypedContractMethod<[_day: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetRewardCounters"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardPerWinPerDay"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "server"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReferralContract"
  ): TypedContractMethod<[_contract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setServer"
  ): TypedContractMethod<[_server: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitSaltedGuess"
  ): TypedContractMethod<
    [
      _collectionId: BigNumberish,
      _saltedGuess: BytesLike,
      _commitment: BytesLike,
      _serverSignature: BytesLike,
      _shouldFlag: boolean
    ],
    [[boolean, bigint] & { isCorrect: boolean; attempts: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "totalFlaggedWallets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPaid"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReferralEarned"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReferralRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReferralsClaimed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWinnerRewardsClaimed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWinnerRewardsDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWins"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWinsPerDay"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "unflagWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userSessions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[string, boolean] & { commitment: string; hasWonToday: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "winsPerCollection"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "winsPerDayPerCollection"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CommitmentSet"
  ): TypedContractEvent<
    CommitmentSetEvent.InputTuple,
    CommitmentSetEvent.OutputTuple,
    CommitmentSetEvent.OutputObject
  >;
  getEvent(
    key: "DailyBonusAdded"
  ): TypedContractEvent<
    DailyBonusAddedEvent.InputTuple,
    DailyBonusAddedEvent.OutputTuple,
    DailyBonusAddedEvent.OutputObject
  >;
  getEvent(
    key: "SaltedGuessMade"
  ): TypedContractEvent<
    SaltedGuessMadeEvent.InputTuple,
    SaltedGuessMadeEvent.OutputTuple,
    SaltedGuessMadeEvent.OutputObject
  >;
  getEvent(
    key: "WalletFlagged"
  ): TypedContractEvent<
    WalletFlaggedEvent.InputTuple,
    WalletFlaggedEvent.OutputTuple,
    WalletFlaggedEvent.OutputObject
  >;
  getEvent(
    key: "WalletUnflagged"
  ): TypedContractEvent<
    WalletUnflaggedEvent.InputTuple,
    WalletUnflaggedEvent.OutputTuple,
    WalletUnflaggedEvent.OutputObject
  >;
  getEvent(
    key: "WinRecorded"
  ): TypedContractEvent<
    WinRecordedEvent.InputTuple,
    WinRecordedEvent.OutputTuple,
    WinRecordedEvent.OutputObject
  >;

  filters: {
    "CommitmentSet(address,uint256,uint256,bytes32)": TypedContractEvent<
      CommitmentSetEvent.InputTuple,
      CommitmentSetEvent.OutputTuple,
      CommitmentSetEvent.OutputObject
    >;
    CommitmentSet: TypedContractEvent<
      CommitmentSetEvent.InputTuple,
      CommitmentSetEvent.OutputTuple,
      CommitmentSetEvent.OutputObject
    >;

    "DailyBonusAdded(uint256,uint256,address)": TypedContractEvent<
      DailyBonusAddedEvent.InputTuple,
      DailyBonusAddedEvent.OutputTuple,
      DailyBonusAddedEvent.OutputObject
    >;
    DailyBonusAdded: TypedContractEvent<
      DailyBonusAddedEvent.InputTuple,
      DailyBonusAddedEvent.OutputTuple,
      DailyBonusAddedEvent.OutputObject
    >;

    "SaltedGuessMade(address,uint256,bytes32,bool,uint256)": TypedContractEvent<
      SaltedGuessMadeEvent.InputTuple,
      SaltedGuessMadeEvent.OutputTuple,
      SaltedGuessMadeEvent.OutputObject
    >;
    SaltedGuessMade: TypedContractEvent<
      SaltedGuessMadeEvent.InputTuple,
      SaltedGuessMadeEvent.OutputTuple,
      SaltedGuessMadeEvent.OutputObject
    >;

    "WalletFlagged(address,string)": TypedContractEvent<
      WalletFlaggedEvent.InputTuple,
      WalletFlaggedEvent.OutputTuple,
      WalletFlaggedEvent.OutputObject
    >;
    WalletFlagged: TypedContractEvent<
      WalletFlaggedEvent.InputTuple,
      WalletFlaggedEvent.OutputTuple,
      WalletFlaggedEvent.OutputObject
    >;

    "WalletUnflagged(address)": TypedContractEvent<
      WalletUnflaggedEvent.InputTuple,
      WalletUnflaggedEvent.OutputTuple,
      WalletUnflaggedEvent.OutputObject
    >;
    WalletUnflagged: TypedContractEvent<
      WalletUnflaggedEvent.InputTuple,
      WalletUnflaggedEvent.OutputTuple,
      WalletUnflaggedEvent.OutputObject
    >;

    "WinRecorded(address,uint256,uint256)": TypedContractEvent<
      WinRecordedEvent.InputTuple,
      WinRecordedEvent.OutputTuple,
      WinRecordedEvent.OutputObject
    >;
    WinRecorded: TypedContractEvent<
      WinRecordedEvent.InputTuple,
      WinRecordedEvent.OutputTuple,
      WinRecordedEvent.OutputObject
    >;
  };
}
