/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Quizzdle {
  export type GuessStruct = {
    player: AddressLike;
    collectionId: BigNumberish;
    characterId: BigNumberish;
    timestamp: BigNumberish;
    isCorrect: boolean;
  };

  export type GuessStructOutput = [
    player: string,
    collectionId: bigint,
    characterId: bigint,
    timestamp: bigint,
    isCorrect: boolean
  ] & {
    player: string;
    collectionId: bigint;
    characterId: bigint;
    timestamp: bigint;
    isCorrect: boolean;
  };
}

export interface QuizzdleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRevenue"
      | "attemptsPerDay"
      | "claimReferralRewards"
      | "claimWinnerRewards"
      | "claimedDays"
      | "collectionCharacterIds"
      | "collectionExists"
      | "dailyRevenue"
      | "dayFinalized"
      | "feePerGuess"
      | "getAttempts"
      | "getCollectionCharacterIds"
      | "getCurrentDay"
      | "getDailyCharacterId"
      | "getGlobalTotalPaid"
      | "getGlobalTotalWins"
      | "getPendingWinnerRewards"
      | "getPlayerGuesses"
      | "getPlayerWinsForDay"
      | "getTotalPaid"
      | "getTotalReferralEarned"
      | "getTotalWinnersCount"
      | "getTotalWins"
      | "getWinnersTodayCount"
      | "getWinsPerCollection"
      | "globalTotalPaid"
      | "globalTotalWins"
      | "hasClaimedDay"
      | "hasWonEver"
      | "lastProcessedDay"
      | "makeGuess"
      | "owner"
      | "pendingReferralRewards"
      | "playerGuesses"
      | "playerTotalWinsPerDay"
      | "referralContract"
      | "referralRewards"
      | "rewardPerWinPerDay"
      | "setFee"
      | "setReferralContract"
      | "setSalt"
      | "totalPaid"
      | "totalReferralEarned"
      | "totalReferralRewards"
      | "totalReferralsClaimed"
      | "totalWinnerRewardsClaimed"
      | "totalWinnerRewardsDistributed"
      | "totalWinnersCount"
      | "totalWins"
      | "totalWinsPerDay"
      | "updateCollectionCharacterIds"
      | "updateMultipleCollections"
      | "verifyGuess"
      | "winnersTodayCount"
      | "winsPerCollection"
      | "winsPerDay"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollectionUpdated"
      | "CollectionsUpdated"
      | "DayFinalized"
      | "FeeUpdated"
      | "FundsWithdrawn"
      | "GuessMade"
      | "ReferralContractUpdated"
      | "ReferralRewardCredited"
      | "ReferralRewardsClaimed"
      | "RevenueAdded"
      | "SaltUpdated"
      | "WinnerRewardsClaimed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "addRevenue", values: [string]): string;
  encodeFunctionData(
    functionFragment: "attemptsPerDay",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReferralRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnerRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedDays",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionCharacterIds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dayFinalized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feePerGuess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAttempts",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionCharacterIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyCharacterId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalTotalPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalTotalWins",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingWinnerRewards",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerGuesses",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerWinsForDay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPaid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalReferralEarned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalWinnersCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalWins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinnersTodayCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinsPerCollection",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "globalTotalPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalTotalWins",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedDay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasWonEver",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastProcessedDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "makeGuess",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingReferralRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerGuesses",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerTotalWinsPerDay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "referralContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPerWinPerDay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferralContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setSalt", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "totalPaid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReferralEarned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReferralRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReferralsClaimed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWinnerRewardsClaimed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWinnerRewardsDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWinnersCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWinsPerDay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCollectionCharacterIds",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMultipleCollections",
    values: [BigNumberish[], BigNumberish[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyGuess",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winnersTodayCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winsPerCollection",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winsPerDay",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addRevenue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attemptsPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReferralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnerRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectionCharacterIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectionExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dayFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feePerGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttempts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionCharacterIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyCharacterId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalTotalPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalTotalWins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingWinnerRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerGuesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerWinsForDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalReferralEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalWinnersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalWins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinnersTodayCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinsPerCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalTotalPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalTotalWins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasWonEver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastProcessedDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "makeGuess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingReferralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerGuesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerTotalWinsPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPerWinPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReferralContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSalt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalPaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalReferralEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReferralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReferralsClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWinnerRewardsClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWinnerRewardsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWinnersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalWins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalWinsPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCollectionCharacterIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMultipleCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winnersTodayCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winsPerCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winsPerDay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CollectionUpdatedEvent {
  export type InputTuple = [
    collectionId: BigNumberish,
    characterCount: BigNumberish
  ];
  export type OutputTuple = [collectionId: bigint, characterCount: bigint];
  export interface OutputObject {
    collectionId: bigint;
    characterCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollectionsUpdatedEvent {
  export type InputTuple = [collectionIds: BigNumberish[]];
  export type OutputTuple = [collectionIds: bigint[]];
  export interface OutputObject {
    collectionIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DayFinalizedEvent {
  export type InputTuple = [
    day: BigNumberish,
    totalRevenue: BigNumberish,
    totalWins: BigNumberish,
    rewardPerWin: BigNumberish
  ];
  export type OutputTuple = [
    day: bigint,
    totalRevenue: bigint,
    totalWins: bigint,
    rewardPerWin: bigint
  ];
  export interface OutputObject {
    day: bigint;
    totalRevenue: bigint;
    totalWins: bigint;
    rewardPerWin: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuessMadeEvent {
  export type InputTuple = [
    player: AddressLike,
    collectionId: BigNumberish,
    characterId: BigNumberish,
    isCorrect: boolean,
    attempts: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    collectionId: bigint,
    characterId: bigint,
    isCorrect: boolean,
    attempts: bigint
  ];
  export interface OutputObject {
    player: string;
    collectionId: bigint;
    characterId: bigint;
    isCorrect: boolean;
    attempts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralContractUpdatedEvent {
  export type InputTuple = [newContract: AddressLike];
  export type OutputTuple = [newContract: string];
  export interface OutputObject {
    newContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRewardCreditedEvent {
  export type InputTuple = [
    referrer: AddressLike,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [referrer: string, player: string, amount: bigint];
  export interface OutputObject {
    referrer: string;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRewardsClaimedEvent {
  export type InputTuple = [referrer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [referrer: string, amount: bigint];
  export interface OutputObject {
    referrer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueAddedEvent {
  export type InputTuple = [
    day: BigNumberish,
    amount: BigNumberish,
    source: string
  ];
  export type OutputTuple = [day: bigint, amount: bigint, source: string];
  export interface OutputObject {
    day: bigint;
    amount: bigint;
    source: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaltUpdatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerRewardsClaimedEvent {
  export type InputTuple = [
    player: AddressLike,
    day: BigNumberish,
    amount: BigNumberish,
    wins: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    day: bigint,
    amount: bigint,
    wins: bigint
  ];
  export interface OutputObject {
    player: string;
    day: bigint;
    amount: bigint;
    wins: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Quizzdle extends BaseContract {
  connect(runner?: ContractRunner | null): Quizzdle;
  waitForDeployment(): Promise<this>;

  interface: QuizzdleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRevenue: TypedContractMethod<[_source: string], [void], "payable">;

  attemptsPerDay: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  claimReferralRewards: TypedContractMethod<[], [void], "nonpayable">;

  claimWinnerRewards: TypedContractMethod<
    [_day: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimedDays: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  collectionCharacterIds: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  collectionExists: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  dailyRevenue: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dayFinalized: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  feePerGuess: TypedContractMethod<[], [bigint], "view">;

  getAttempts: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish, _day: BigNumberish],
    [bigint],
    "view"
  >;

  getCollectionCharacterIds: TypedContractMethod<
    [_collectionId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getCurrentDay: TypedContractMethod<[], [bigint], "view">;

  getDailyCharacterId: TypedContractMethod<
    [_collectionId: BigNumberish],
    [bigint],
    "view"
  >;

  getGlobalTotalPaid: TypedContractMethod<[], [bigint], "view">;

  getGlobalTotalWins: TypedContractMethod<[], [bigint], "view">;

  getPendingWinnerRewards: TypedContractMethod<
    [_player: AddressLike, _day: BigNumberish],
    [bigint],
    "view"
  >;

  getPlayerGuesses: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [Quizzdle.GuessStructOutput[]],
    "view"
  >;

  getPlayerWinsForDay: TypedContractMethod<
    [_player: AddressLike, _day: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalPaid: TypedContractMethod<[_player: AddressLike], [bigint], "view">;

  getTotalReferralEarned: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  getTotalWinnersCount: TypedContractMethod<
    [_collectionId: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalWins: TypedContractMethod<[_player: AddressLike], [bigint], "view">;

  getWinnersTodayCount: TypedContractMethod<
    [_collectionId: BigNumberish, _day: BigNumberish],
    [bigint],
    "view"
  >;

  getWinsPerCollection: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [bigint],
    "view"
  >;

  globalTotalPaid: TypedContractMethod<[], [bigint], "view">;

  globalTotalWins: TypedContractMethod<[], [bigint], "view">;

  hasClaimedDay: TypedContractMethod<
    [_player: AddressLike, _day: BigNumberish],
    [boolean],
    "view"
  >;

  hasWonEver: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  lastProcessedDay: TypedContractMethod<[], [bigint], "view">;

  makeGuess: TypedContractMethod<
    [_collectionId: BigNumberish, _characterId: BigNumberish],
    [[boolean, bigint] & { isCorrect: boolean; attempts: bigint }],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingReferralRewards: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  playerGuesses: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        player: string;
        collectionId: bigint;
        characterId: bigint;
        timestamp: bigint;
        isCorrect: boolean;
      }
    ],
    "view"
  >;

  playerTotalWinsPerDay: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  referralContract: TypedContractMethod<[], [string], "view">;

  referralRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  rewardPerWinPerDay: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  setFee: TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;

  setReferralContract: TypedContractMethod<
    [_referralContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setSalt: TypedContractMethod<[_newSalt: BytesLike], [void], "nonpayable">;

  totalPaid: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalReferralEarned: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  totalReferralRewards: TypedContractMethod<[], [bigint], "view">;

  totalReferralsClaimed: TypedContractMethod<[], [bigint], "view">;

  totalWinnerRewardsClaimed: TypedContractMethod<[], [bigint], "view">;

  totalWinnerRewardsDistributed: TypedContractMethod<[], [bigint], "view">;

  totalWinnersCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  totalWins: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalWinsPerDay: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  updateCollectionCharacterIds: TypedContractMethod<
    [_collectionId: BigNumberish, _characterIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  updateMultipleCollections: TypedContractMethod<
    [_collectionIds: BigNumberish[], _characterIdsArrays: BigNumberish[][]],
    [void],
    "nonpayable"
  >;

  verifyGuess: TypedContractMethod<
    [_collectionId: BigNumberish, _characterId: BigNumberish],
    [boolean],
    "view"
  >;

  winnersTodayCount: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  winsPerCollection: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  winsPerDay: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [bigint],
    "view"
  >;

  withdraw: TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRevenue"
  ): TypedContractMethod<[_source: string], [void], "payable">;
  getFunction(
    nameOrSignature: "attemptsPerDay"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimReferralRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnerRewards"
  ): TypedContractMethod<[_day: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedDays"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectionCharacterIds"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectionExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "dailyRevenue"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dayFinalized"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "feePerGuess"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAttempts"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish, _day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCollectionCharacterIds"
  ): TypedContractMethod<[_collectionId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCurrentDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDailyCharacterId"
  ): TypedContractMethod<[_collectionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGlobalTotalPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGlobalTotalWins"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingWinnerRewards"
  ): TypedContractMethod<
    [_player: AddressLike, _day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerGuesses"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [Quizzdle.GuessStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerWinsForDay"
  ): TypedContractMethod<
    [_player: AddressLike, _day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPaid"
  ): TypedContractMethod<[_player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalReferralEarned"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalWinnersCount"
  ): TypedContractMethod<[_collectionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalWins"
  ): TypedContractMethod<[_player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWinnersTodayCount"
  ): TypedContractMethod<
    [_collectionId: BigNumberish, _day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinsPerCollection"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalTotalPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalTotalWins"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasClaimedDay"
  ): TypedContractMethod<
    [_player: AddressLike, _day: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasWonEver"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastProcessedDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "makeGuess"
  ): TypedContractMethod<
    [_collectionId: BigNumberish, _characterId: BigNumberish],
    [[boolean, bigint] & { isCorrect: boolean; attempts: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingReferralRewards"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "playerGuesses"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        player: string;
        collectionId: bigint;
        characterId: bigint;
        timestamp: bigint;
        isCorrect: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerTotalWinsPerDay"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "referralContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referralRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardPerWinPerDay"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReferralContract"
  ): TypedContractMethod<
    [_referralContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSalt"
  ): TypedContractMethod<[_newSalt: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPaid"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReferralEarned"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReferralRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReferralsClaimed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWinnerRewardsClaimed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWinnerRewardsDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWinnersCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWins"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWinsPerDay"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateCollectionCharacterIds"
  ): TypedContractMethod<
    [_collectionId: BigNumberish, _characterIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMultipleCollections"
  ): TypedContractMethod<
    [_collectionIds: BigNumberish[], _characterIdsArrays: BigNumberish[][]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyGuess"
  ): TypedContractMethod<
    [_collectionId: BigNumberish, _characterId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "winnersTodayCount"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "winsPerCollection"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "winsPerDay"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CollectionUpdated"
  ): TypedContractEvent<
    CollectionUpdatedEvent.InputTuple,
    CollectionUpdatedEvent.OutputTuple,
    CollectionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CollectionsUpdated"
  ): TypedContractEvent<
    CollectionsUpdatedEvent.InputTuple,
    CollectionsUpdatedEvent.OutputTuple,
    CollectionsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DayFinalized"
  ): TypedContractEvent<
    DayFinalizedEvent.InputTuple,
    DayFinalizedEvent.OutputTuple,
    DayFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "GuessMade"
  ): TypedContractEvent<
    GuessMadeEvent.InputTuple,
    GuessMadeEvent.OutputTuple,
    GuessMadeEvent.OutputObject
  >;
  getEvent(
    key: "ReferralContractUpdated"
  ): TypedContractEvent<
    ReferralContractUpdatedEvent.InputTuple,
    ReferralContractUpdatedEvent.OutputTuple,
    ReferralContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRewardCredited"
  ): TypedContractEvent<
    ReferralRewardCreditedEvent.InputTuple,
    ReferralRewardCreditedEvent.OutputTuple,
    ReferralRewardCreditedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRewardsClaimed"
  ): TypedContractEvent<
    ReferralRewardsClaimedEvent.InputTuple,
    ReferralRewardsClaimedEvent.OutputTuple,
    ReferralRewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RevenueAdded"
  ): TypedContractEvent<
    RevenueAddedEvent.InputTuple,
    RevenueAddedEvent.OutputTuple,
    RevenueAddedEvent.OutputObject
  >;
  getEvent(
    key: "SaltUpdated"
  ): TypedContractEvent<
    SaltUpdatedEvent.InputTuple,
    SaltUpdatedEvent.OutputTuple,
    SaltUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerRewardsClaimed"
  ): TypedContractEvent<
    WinnerRewardsClaimedEvent.InputTuple,
    WinnerRewardsClaimedEvent.OutputTuple,
    WinnerRewardsClaimedEvent.OutputObject
  >;

  filters: {
    "CollectionUpdated(uint256,uint256)": TypedContractEvent<
      CollectionUpdatedEvent.InputTuple,
      CollectionUpdatedEvent.OutputTuple,
      CollectionUpdatedEvent.OutputObject
    >;
    CollectionUpdated: TypedContractEvent<
      CollectionUpdatedEvent.InputTuple,
      CollectionUpdatedEvent.OutputTuple,
      CollectionUpdatedEvent.OutputObject
    >;

    "CollectionsUpdated(uint256[])": TypedContractEvent<
      CollectionsUpdatedEvent.InputTuple,
      CollectionsUpdatedEvent.OutputTuple,
      CollectionsUpdatedEvent.OutputObject
    >;
    CollectionsUpdated: TypedContractEvent<
      CollectionsUpdatedEvent.InputTuple,
      CollectionsUpdatedEvent.OutputTuple,
      CollectionsUpdatedEvent.OutputObject
    >;

    "DayFinalized(uint256,uint256,uint256,uint256)": TypedContractEvent<
      DayFinalizedEvent.InputTuple,
      DayFinalizedEvent.OutputTuple,
      DayFinalizedEvent.OutputObject
    >;
    DayFinalized: TypedContractEvent<
      DayFinalizedEvent.InputTuple,
      DayFinalizedEvent.OutputTuple,
      DayFinalizedEvent.OutputObject
    >;

    "FeeUpdated(uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "GuessMade(address,uint256,uint256,bool,uint256)": TypedContractEvent<
      GuessMadeEvent.InputTuple,
      GuessMadeEvent.OutputTuple,
      GuessMadeEvent.OutputObject
    >;
    GuessMade: TypedContractEvent<
      GuessMadeEvent.InputTuple,
      GuessMadeEvent.OutputTuple,
      GuessMadeEvent.OutputObject
    >;

    "ReferralContractUpdated(address)": TypedContractEvent<
      ReferralContractUpdatedEvent.InputTuple,
      ReferralContractUpdatedEvent.OutputTuple,
      ReferralContractUpdatedEvent.OutputObject
    >;
    ReferralContractUpdated: TypedContractEvent<
      ReferralContractUpdatedEvent.InputTuple,
      ReferralContractUpdatedEvent.OutputTuple,
      ReferralContractUpdatedEvent.OutputObject
    >;

    "ReferralRewardCredited(address,address,uint256)": TypedContractEvent<
      ReferralRewardCreditedEvent.InputTuple,
      ReferralRewardCreditedEvent.OutputTuple,
      ReferralRewardCreditedEvent.OutputObject
    >;
    ReferralRewardCredited: TypedContractEvent<
      ReferralRewardCreditedEvent.InputTuple,
      ReferralRewardCreditedEvent.OutputTuple,
      ReferralRewardCreditedEvent.OutputObject
    >;

    "ReferralRewardsClaimed(address,uint256)": TypedContractEvent<
      ReferralRewardsClaimedEvent.InputTuple,
      ReferralRewardsClaimedEvent.OutputTuple,
      ReferralRewardsClaimedEvent.OutputObject
    >;
    ReferralRewardsClaimed: TypedContractEvent<
      ReferralRewardsClaimedEvent.InputTuple,
      ReferralRewardsClaimedEvent.OutputTuple,
      ReferralRewardsClaimedEvent.OutputObject
    >;

    "RevenueAdded(uint256,uint256,string)": TypedContractEvent<
      RevenueAddedEvent.InputTuple,
      RevenueAddedEvent.OutputTuple,
      RevenueAddedEvent.OutputObject
    >;
    RevenueAdded: TypedContractEvent<
      RevenueAddedEvent.InputTuple,
      RevenueAddedEvent.OutputTuple,
      RevenueAddedEvent.OutputObject
    >;

    "SaltUpdated()": TypedContractEvent<
      SaltUpdatedEvent.InputTuple,
      SaltUpdatedEvent.OutputTuple,
      SaltUpdatedEvent.OutputObject
    >;
    SaltUpdated: TypedContractEvent<
      SaltUpdatedEvent.InputTuple,
      SaltUpdatedEvent.OutputTuple,
      SaltUpdatedEvent.OutputObject
    >;

    "WinnerRewardsClaimed(address,uint256,uint256,uint256)": TypedContractEvent<
      WinnerRewardsClaimedEvent.InputTuple,
      WinnerRewardsClaimedEvent.OutputTuple,
      WinnerRewardsClaimedEvent.OutputObject
    >;
    WinnerRewardsClaimed: TypedContractEvent<
      WinnerRewardsClaimedEvent.InputTuple,
      WinnerRewardsClaimedEvent.OutputTuple,
      WinnerRewardsClaimedEvent.OutputObject
    >;
  };
}
