/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Dailydle {
  export type GuessStruct = {
    player: AddressLike;
    collectionId: BigNumberish;
    characterId: BigNumberish;
    timestamp: BigNumberish;
    isCorrect: boolean;
  };

  export type GuessStructOutput = [
    player: string,
    collectionId: bigint,
    characterId: bigint,
    timestamp: bigint,
    isCorrect: boolean
  ] & {
    player: string;
    collectionId: bigint;
    characterId: bigint;
    timestamp: bigint;
    isCorrect: boolean;
  };
}

export interface DailydleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attemptsPerDay"
      | "collectionCharacterIds"
      | "collectionExists"
      | "getAttempts"
      | "getCollectionCharacterIds"
      | "getDailyCharacterId"
      | "getPlayerGuesses"
      | "getTotalWinnersCount"
      | "getTotalWins"
      | "getWinnersTodayCount"
      | "getWinsPerCollection"
      | "hasWonEver"
      | "hasWonToday"
      | "makeGuess"
      | "playerGuesses"
      | "totalWinnersCount"
      | "totalWins"
      | "updateCollectionCharacterIds"
      | "updateMultipleCollections"
      | "verifyGuess"
      | "winnersTodayCount"
      | "winsPerCollection"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollectionUpdated"
      | "CollectionsUpdated"
      | "GuessMade"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attemptsPerDay",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionCharacterIds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttempts",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionCharacterIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyCharacterId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerGuesses",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalWinnersCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalWins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinnersTodayCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinsPerCollection",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasWonEver",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasWonToday",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makeGuess",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerGuesses",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWinnersCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCollectionCharacterIds",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMultipleCollections",
    values: [BigNumberish[], BigNumberish[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyGuess",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winnersTodayCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winsPerCollection",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "attemptsPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectionCharacterIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectionExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttempts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionCharacterIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyCharacterId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerGuesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalWinnersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalWins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinnersTodayCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinsPerCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasWonEver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasWonToday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "makeGuess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerGuesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWinnersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalWins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateCollectionCharacterIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMultipleCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winnersTodayCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winsPerCollection",
    data: BytesLike
  ): Result;
}

export namespace CollectionUpdatedEvent {
  export type InputTuple = [
    collectionId: BigNumberish,
    characterCount: BigNumberish
  ];
  export type OutputTuple = [collectionId: bigint, characterCount: bigint];
  export interface OutputObject {
    collectionId: bigint;
    characterCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollectionsUpdatedEvent {
  export type InputTuple = [collectionIds: BigNumberish[]];
  export type OutputTuple = [collectionIds: bigint[]];
  export interface OutputObject {
    collectionIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuessMadeEvent {
  export type InputTuple = [
    player: AddressLike,
    collectionId: BigNumberish,
    characterId: BigNumberish,
    isCorrect: boolean,
    attempts: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    collectionId: bigint,
    characterId: bigint,
    isCorrect: boolean,
    attempts: bigint
  ];
  export interface OutputObject {
    player: string;
    collectionId: bigint;
    characterId: bigint;
    isCorrect: boolean;
    attempts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Dailydle extends BaseContract {
  connect(runner?: ContractRunner | null): Dailydle;
  waitForDeployment(): Promise<this>;

  interface: DailydleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attemptsPerDay: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  collectionCharacterIds: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  collectionExists: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  getAttempts: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish, _day: BigNumberish],
    [bigint],
    "view"
  >;

  getCollectionCharacterIds: TypedContractMethod<
    [_collectionId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getDailyCharacterId: TypedContractMethod<
    [_collectionId: BigNumberish],
    [bigint],
    "view"
  >;

  getPlayerGuesses: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [Dailydle.GuessStructOutput[]],
    "view"
  >;

  getTotalWinnersCount: TypedContractMethod<
    [_collectionId: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalWins: TypedContractMethod<[_player: AddressLike], [bigint], "view">;

  getWinnersTodayCount: TypedContractMethod<
    [_collectionId: BigNumberish, _day: BigNumberish],
    [bigint],
    "view"
  >;

  getWinsPerCollection: TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [bigint],
    "view"
  >;

  hasWonEver: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasWonToday: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;

  makeGuess: TypedContractMethod<
    [_collectionId: BigNumberish, _characterId: BigNumberish],
    [[boolean, bigint] & { isCorrect: boolean; attempts: bigint }],
    "nonpayable"
  >;

  playerGuesses: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        player: string;
        collectionId: bigint;
        characterId: bigint;
        timestamp: bigint;
        isCorrect: boolean;
      }
    ],
    "view"
  >;

  totalWinnersCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  totalWins: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  updateCollectionCharacterIds: TypedContractMethod<
    [_collectionId: BigNumberish, _characterIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  updateMultipleCollections: TypedContractMethod<
    [_collectionIds: BigNumberish[], _characterIdsArrays: BigNumberish[][]],
    [void],
    "nonpayable"
  >;

  verifyGuess: TypedContractMethod<
    [_collectionId: BigNumberish, _characterId: BigNumberish],
    [boolean],
    "view"
  >;

  winnersTodayCount: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  winsPerCollection: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attemptsPerDay"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectionCharacterIds"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectionExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAttempts"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish, _day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCollectionCharacterIds"
  ): TypedContractMethod<[_collectionId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDailyCharacterId"
  ): TypedContractMethod<[_collectionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerGuesses"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [Dailydle.GuessStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalWinnersCount"
  ): TypedContractMethod<[_collectionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalWins"
  ): TypedContractMethod<[_player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWinnersTodayCount"
  ): TypedContractMethod<
    [_collectionId: BigNumberish, _day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinsPerCollection"
  ): TypedContractMethod<
    [_player: AddressLike, _collectionId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasWonEver"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasWonToday"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "makeGuess"
  ): TypedContractMethod<
    [_collectionId: BigNumberish, _characterId: BigNumberish],
    [[boolean, bigint] & { isCorrect: boolean; attempts: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "playerGuesses"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        player: string;
        collectionId: bigint;
        characterId: bigint;
        timestamp: bigint;
        isCorrect: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalWinnersCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWins"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateCollectionCharacterIds"
  ): TypedContractMethod<
    [_collectionId: BigNumberish, _characterIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMultipleCollections"
  ): TypedContractMethod<
    [_collectionIds: BigNumberish[], _characterIdsArrays: BigNumberish[][]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyGuess"
  ): TypedContractMethod<
    [_collectionId: BigNumberish, _characterId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "winnersTodayCount"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "winsPerCollection"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "CollectionUpdated"
  ): TypedContractEvent<
    CollectionUpdatedEvent.InputTuple,
    CollectionUpdatedEvent.OutputTuple,
    CollectionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CollectionsUpdated"
  ): TypedContractEvent<
    CollectionsUpdatedEvent.InputTuple,
    CollectionsUpdatedEvent.OutputTuple,
    CollectionsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GuessMade"
  ): TypedContractEvent<
    GuessMadeEvent.InputTuple,
    GuessMadeEvent.OutputTuple,
    GuessMadeEvent.OutputObject
  >;

  filters: {
    "CollectionUpdated(uint256,uint256)": TypedContractEvent<
      CollectionUpdatedEvent.InputTuple,
      CollectionUpdatedEvent.OutputTuple,
      CollectionUpdatedEvent.OutputObject
    >;
    CollectionUpdated: TypedContractEvent<
      CollectionUpdatedEvent.InputTuple,
      CollectionUpdatedEvent.OutputTuple,
      CollectionUpdatedEvent.OutputObject
    >;

    "CollectionsUpdated(uint256[])": TypedContractEvent<
      CollectionsUpdatedEvent.InputTuple,
      CollectionsUpdatedEvent.OutputTuple,
      CollectionsUpdatedEvent.OutputObject
    >;
    CollectionsUpdated: TypedContractEvent<
      CollectionsUpdatedEvent.InputTuple,
      CollectionsUpdatedEvent.OutputTuple,
      CollectionsUpdatedEvent.OutputObject
    >;

    "GuessMade(address,uint256,uint256,bool,uint256)": TypedContractEvent<
      GuessMadeEvent.InputTuple,
      GuessMadeEvent.OutputTuple,
      GuessMadeEvent.OutputObject
    >;
    GuessMade: TypedContractEvent<
      GuessMadeEvent.InputTuple,
      GuessMadeEvent.OutputTuple,
      GuessMadeEvent.OutputObject
    >;
  };
}
