/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GmQuizzdleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canGmToday"
      | "currentStreak"
      | "getAllPlayersLongestStreaks"
      | "getEffectiveStreak"
      | "getGlobalStats"
      | "getPlayerStats"
      | "getPlayersCount"
      | "gm"
      | "hasPlayedBefore"
      | "isStreakActive"
      | "lastGmDay"
      | "longestStreak"
      | "owner"
      | "players"
      | "totalGms"
      | "totalGmsGlobal"
      | "uniquePlayers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GmSent" | "NewLongestStreak" | "StreakBroken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canGmToday",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentStreak",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPlayersLongestStreaks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEffectiveStreak",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayersCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasPlayedBefore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isStreakActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastGmDay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "longestStreak",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "players",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalGms",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalGmsGlobal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniquePlayers",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "canGmToday", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentStreak",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPlayersLongestStreaks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEffectiveStreak",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasPlayedBefore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStreakActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastGmDay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "longestStreak",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "players", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalGms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalGmsGlobal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniquePlayers",
    data: BytesLike
  ): Result;
}

export namespace GmSentEvent {
  export type InputTuple = [
    player: AddressLike,
    streak: BigNumberish,
    day: BigNumberish
  ];
  export type OutputTuple = [player: string, streak: bigint, day: bigint];
  export interface OutputObject {
    player: string;
    streak: bigint;
    day: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewLongestStreakEvent {
  export type InputTuple = [player: AddressLike, streak: BigNumberish];
  export type OutputTuple = [player: string, streak: bigint];
  export interface OutputObject {
    player: string;
    streak: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreakBrokenEvent {
  export type InputTuple = [player: AddressLike, previousStreak: BigNumberish];
  export type OutputTuple = [player: string, previousStreak: bigint];
  export interface OutputObject {
    player: string;
    previousStreak: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GmQuizzdle extends BaseContract {
  connect(runner?: ContractRunner | null): GmQuizzdle;
  waitForDeployment(): Promise<this>;

  interface: GmQuizzdleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canGmToday: TypedContractMethod<[_player: AddressLike], [boolean], "view">;

  currentStreak: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getAllPlayersLongestStreaks: TypedContractMethod<
    [],
    [
      [string[], bigint[]] & {
        playerAddresses: string[];
        longestStreaks: bigint[];
      }
    ],
    "view"
  >;

  getEffectiveStreak: TypedContractMethod<
    [_player: AddressLike],
    [bigint],
    "view"
  >;

  getGlobalStats: TypedContractMethod<
    [],
    [[bigint, bigint] & { totalGms_: bigint; uniquePlayers_: bigint }],
    "view"
  >;

  getPlayerStats: TypedContractMethod<
    [_player: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean] & {
        streak: bigint;
        longest: bigint;
        total: bigint;
        canGm: boolean;
        streakActive: boolean;
      }
    ],
    "view"
  >;

  getPlayersCount: TypedContractMethod<[], [bigint], "view">;

  gm: TypedContractMethod<[], [void], "nonpayable">;

  hasPlayedBefore: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isStreakActive: TypedContractMethod<
    [_player: AddressLike],
    [boolean],
    "view"
  >;

  lastGmDay: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  longestStreak: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  players: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  totalGms: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalGmsGlobal: TypedContractMethod<[], [bigint], "view">;

  uniquePlayers: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canGmToday"
  ): TypedContractMethod<[_player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "currentStreak"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllPlayersLongestStreaks"
  ): TypedContractMethod<
    [],
    [
      [string[], bigint[]] & {
        playerAddresses: string[];
        longestStreaks: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEffectiveStreak"
  ): TypedContractMethod<[_player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { totalGms_: bigint; uniquePlayers_: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [_player: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean] & {
        streak: bigint;
        longest: bigint;
        total: bigint;
        canGm: boolean;
        streakActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayersCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gm"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasPlayedBefore"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isStreakActive"
  ): TypedContractMethod<[_player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastGmDay"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "longestStreak"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "players"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalGms"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalGmsGlobal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "uniquePlayers"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "GmSent"
  ): TypedContractEvent<
    GmSentEvent.InputTuple,
    GmSentEvent.OutputTuple,
    GmSentEvent.OutputObject
  >;
  getEvent(
    key: "NewLongestStreak"
  ): TypedContractEvent<
    NewLongestStreakEvent.InputTuple,
    NewLongestStreakEvent.OutputTuple,
    NewLongestStreakEvent.OutputObject
  >;
  getEvent(
    key: "StreakBroken"
  ): TypedContractEvent<
    StreakBrokenEvent.InputTuple,
    StreakBrokenEvent.OutputTuple,
    StreakBrokenEvent.OutputObject
  >;

  filters: {
    "GmSent(address,uint256,uint256)": TypedContractEvent<
      GmSentEvent.InputTuple,
      GmSentEvent.OutputTuple,
      GmSentEvent.OutputObject
    >;
    GmSent: TypedContractEvent<
      GmSentEvent.InputTuple,
      GmSentEvent.OutputTuple,
      GmSentEvent.OutputObject
    >;

    "NewLongestStreak(address,uint256)": TypedContractEvent<
      NewLongestStreakEvent.InputTuple,
      NewLongestStreakEvent.OutputTuple,
      NewLongestStreakEvent.OutputObject
    >;
    NewLongestStreak: TypedContractEvent<
      NewLongestStreakEvent.InputTuple,
      NewLongestStreakEvent.OutputTuple,
      NewLongestStreakEvent.OutputObject
    >;

    "StreakBroken(address,uint256)": TypedContractEvent<
      StreakBrokenEvent.InputTuple,
      StreakBrokenEvent.OutputTuple,
      StreakBrokenEvent.OutputObject
    >;
    StreakBroken: TypedContractEvent<
      StreakBrokenEvent.InputTuple,
      StreakBrokenEvent.OutputTuple,
      StreakBrokenEvent.OutputObject
    >;
  };
}
