/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface QuizzdleReferalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addressToCode"
      | "codeToAddress"
      | "getGlobalStats"
      | "getReferralCount"
      | "getUserReferrals"
      | "getUserStats"
      | "hasRegistered"
      | "isCodeAvailable"
      | "owner"
      | "referrals"
      | "referredBy"
      | "registerWithReferral"
      | "setReferralCode"
      | "totalReferrals"
      | "totalUsers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CodeCreated"
      | "ReferralRegistered"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addressToCode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "codeToAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReferrals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCodeAvailable",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "referrals",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "referredBy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerWithReferral",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferralCode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReferrals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsers",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addressToCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "codeToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReferrals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCodeAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "referrals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "referredBy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerWithReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReferrals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalUsers", data: BytesLike): Result;
}

export namespace CodeCreatedEvent {
  export type InputTuple = [user: AddressLike, code: string];
  export type OutputTuple = [user: string, code: string];
  export interface OutputObject {
    user: string;
    code: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRegisteredEvent {
  export type InputTuple = [
    newUser: AddressLike,
    referrer: AddressLike,
    code: string
  ];
  export type OutputTuple = [newUser: string, referrer: string, code: string];
  export interface OutputObject {
    newUser: string;
    referrer: string;
    code: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuizzdleReferal extends BaseContract {
  connect(runner?: ContractRunner | null): QuizzdleReferal;
  waitForDeployment(): Promise<this>;

  interface: QuizzdleReferalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addressToCode: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  codeToAddress: TypedContractMethod<[arg0: string], [string], "view">;

  getGlobalStats: TypedContractMethod<
    [],
    [[bigint, bigint] & { totalUsers_: bigint; totalReferrals_: bigint }],
    "view"
  >;

  getReferralCount: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  getUserReferrals: TypedContractMethod<
    [_user: AddressLike],
    [string[]],
    "view"
  >;

  getUserStats: TypedContractMethod<
    [_user: AddressLike],
    [
      [string, string, bigint, boolean] & {
        code: string;
        referrer: string;
        referralCount: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  hasRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isCodeAvailable: TypedContractMethod<[_code: string], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  referrals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  referredBy: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  registerWithReferral: TypedContractMethod<
    [_referralCode: string],
    [void],
    "nonpayable"
  >;

  setReferralCode: TypedContractMethod<[_code: string], [void], "nonpayable">;

  totalReferrals: TypedContractMethod<[], [bigint], "view">;

  totalUsers: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addressToCode"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "codeToAddress"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { totalUsers_: bigint; totalReferrals_: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReferralCount"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserReferrals"
  ): TypedContractMethod<[_user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserStats"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [string, string, bigint, boolean] & {
        code: string;
        referrer: string;
        referralCount: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCodeAvailable"
  ): TypedContractMethod<[_code: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referrals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "referredBy"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerWithReferral"
  ): TypedContractMethod<[_referralCode: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReferralCode"
  ): TypedContractMethod<[_code: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalReferrals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUsers"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CodeCreated"
  ): TypedContractEvent<
    CodeCreatedEvent.InputTuple,
    CodeCreatedEvent.OutputTuple,
    CodeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRegistered"
  ): TypedContractEvent<
    ReferralRegisteredEvent.InputTuple,
    ReferralRegisteredEvent.OutputTuple,
    ReferralRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "CodeCreated(address,string)": TypedContractEvent<
      CodeCreatedEvent.InputTuple,
      CodeCreatedEvent.OutputTuple,
      CodeCreatedEvent.OutputObject
    >;
    CodeCreated: TypedContractEvent<
      CodeCreatedEvent.InputTuple,
      CodeCreatedEvent.OutputTuple,
      CodeCreatedEvent.OutputObject
    >;

    "ReferralRegistered(address,address,string)": TypedContractEvent<
      ReferralRegisteredEvent.InputTuple,
      ReferralRegisteredEvent.OutputTuple,
      ReferralRegisteredEvent.OutputObject
    >;
    ReferralRegistered: TypedContractEvent<
      ReferralRegisteredEvent.InputTuple,
      ReferralRegisteredEvent.OutputTuple,
      ReferralRegisteredEvent.OutputObject
    >;

    "UserRegistered(address)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
